generatorName: delphi-whizaxe
outputDir: samples/server/petstore/delphi/whizaxe
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/delphi-whizaxe
additionalProperties:
  hideGenerationTimestamp: "true"
